### ISSUE TITLE
does this work on forge via sinytra connector

### ISSUE THREAD

**Issue by hedkne43rei0pow** [Estecka/mc-Simple-Water-Gravity#3] opened 2024-11-08 20:01 UTC

**Comment by Estecka** [comment] 2024-11-08 20:25
Reportedly yes, but you'll need to open the jar and change the java version to 17 in [`simple-water-gravity.mixins.json`](https://github.com/Estecka/mc-Simple-Water-Gravity/blob/1.21.1/src/main/resources/simple-water-gravity.mixins.json).

If you're on MC 1.20.1 specifically, I may republish a jar that doesn't require such edits.
*Edit: The Java 17 jar is in the release's [additional files](https://modrinth.com/mod/simple-water-gravity/version/1.0.2+1.20.1).*

Closing as duplicate of #2.

**Closed as not planned by Estecka** 2024-11-08 20:25 UTC
Labels: duplicate
